version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint-and-test
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run lint
      - run:
          command: yarn test
          name: Run test

workflows:
  lint:
    jobs:
      - lint-and-test
