version: 2.1

orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@5.4.3

jobs:
  lint-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run lint
      - run:
          command: yarn test
          name: Run test:all
          env:
            DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
            ENV: ${{ secrets.ENV }}
            NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
            DEV_ENDPOINT_ID: ${{ secrets.DEV_ENDPOINT_ID }}
            NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      - codecov/upload

workflows:
  lint-and-test:
    jobs:
      - lint-and-test
