import type { Metadata } from "next";
import "./globals.css";
import MainMenu from "@/components/main-menu/MainMenu";
import React from "react";
import { ViewTransitions } from 'next-view-transitions'
import Backgrounds from "@/components/backgrounds";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  backgrounds,
}: Readonly<{
  children: React.ReactNode;
  backgrounds: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang='en'>
        <body className="overflow-hidden">
          <Backgrounds>
            {backgrounds}
          </Backgrounds>
          <MainMenu/>
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
