import type { Metadata } from "next";
import "./globals.css";
import MainMenu from "@/components/main-menu/MainMenu";
import PagePositioner from "@/components/PagePositioner/PagePositioner";
import React, { unstable_ViewTransition as ViewTransition } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased overflow-hidden">
        <MainMenu />
        {children}
      </body>
    </html>
  );
}
